apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-hpa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: vitorandrietta/go-hpa:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"

          

